# Model configuration
model:
  model_type: "thurstone"
  backbone_model_id: "Tongyi-MAI/Z-Image-Turbo"
  num_transformer_layers: 16
  freeze_backbone: false

  use_ema: true
  ema_decay: 0.995

  use_lora: true
  use_text_features: true
  lora_config:
    r: 32
    lora_alpha: 64
    init_lora_weights: "gaussian"
  
  # Reward head configuration
  use_logistic: false
  visual_head_idx: [4, 8, 12, 16]
  # text_head_idx: [1]
  text_head_idx: [4, 8, 12, 16]
  # text_head_idx: [0]
  use_t_embed: true
  reward_head:
    # conv_type: "2d"
    use_proj_in: True
    width: 1536
    out_dim: 1
    num_queries: 4
    num_attn_heads: 8
    dropout: 0.0
    t_emb_dim: 256


# Training configuration
training:
  mixed_precision: "bf16"  # Options: "fp32", "bf16", "fp16"
  gradient_accumulation_steps: 8
  num_epochs: 1
  uncond_prob: 0.0
  learning_rate: 5e-5
  weight_decay: 0.01
  warmup_steps: 1000
  # lr_scheduler: "cosine"
  lr_scheduler: "constant"

  max_grad_norm: 1.0

  t_weighting_scheme: "uniform"
  t_weighting_scheme_param: 0.0
  
  use_vae: false

  add_noise: true

  
# Data configuration
data:
  train:
    parquet_files: "/path/to/preprocess_data/zimage/part_rank*.parquet"
    bucket_file: "/path/to/preprocess_data/zimage/bucket_index.csv"
    base_batch_size: 1
    reference_size: 1024
    num_workers: 8
    shuffle: true
    seed: 42
    use_dynamic_bsz: false
  eval:
    hpdv3:
      parquet_files: "/path/to/preprocess_data/zimage-test/sample_1000.parquet"
      batch_size: 1
      num_workers: 0
      shuffle: false


# Paths
paths:
  run_name: "ZImage-Thurstone-16layers"
  save_dir: "outputs"

# Logging
logging:
  eval_frac: 1000
  save_frac: 2000
  
# System
system:
  seed: 42